name: Spell Check

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run cspell
        uses: streetsidesoftware/cspell-action@v7
        with:
          config: cspell.json
